### ISSUE TITLE
Topic and keyword terms in study view

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#353]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

To increase the visibility and use of the subject vocabularies, put them higher up in the detailed study view. Now at the bottom. 

The order of keywords in which the keywords are shown could be random.

To be considered and discussed: when it is possible to do a proper keyword search \(restricted to the keyword element\), maybe again show more than 12 keywords, 15-18 keywords? Because it is a very useful way to search.

**Comment by MortenSikt** [comment]
> Are these in conflict: #413 ?

After further inspection, no.

This issue was discussed in the User group. 

- We are satisfied with the current cut off at 12 keywords.
- There is no need to implement a cut off for topics. 

User group agrees that Topics and Keywords should be moved up in the detailed study view. Position should be between "Abstract" and "Methodology". The current format of the elements shall remain.
