### ISSUE TITLE
Change metadata prefix for Kuha2 endpoints

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#388]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Legacy installations of Kuha2 emit non-valid DDI 2.5 XML.

Changing the metadata prefix from oai\_ddi25 to ddi\_c will alleviate the problem.

The affected endpoints are:

ADP

APIS

DNA

SASD

UniData

\(Just check that FSD have upgraded, by looking at recent schema validation results\)

**Comment by john-shepherdson** [comment]
ADP and APIS are still using ddi_c prefix. APIS endpoint appears to have been unreachable since June 2023. ADP only has 6 records under the old prefix.

Remember, endpoint config change are now made in https://github.com/cessda/cessda.cdc.aggregator.deploy/blob/main/charts/harvester/config/config.yaml
