### ISSUE TITLE
UI: Topics and keywords into left bar in detailed study view

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#413]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Move topics and keywords to the left bar in the detailed study view, with a cut-off point.

Cut-off for topics: 6. Cut off for keywords: 15.

Similar results are moved to be below Topics and Keywords.

**Comment by MortenSikt** [comment]
Keywords are currently cut off at 12, having more will give a "read more" button, see: https://datacatalogue.cessda.eu/detail?lang=en&q=b5b5cef69fa436922d5328d538d72ffc924a33229aac9f89fed42709e5327035

Topics appears to not have a cut off based on numbers in this and #353 , see: https://datacatalogue.cessda.eu/detail?lang=en&q=3b4951c1746400c006863d77a2c810e335d241101baf5db774bcdc5950688746

Closing this issue, so that the main issue for this is #353
