### ISSUE TITLE
UI: Changes to results list view

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#415]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Result list changes:

* Shorten abstract to 380 characters in the list.
* Add keywords below. Cut-off point for keywords: max 7 keywords, random chosen \(so as not to have always ones from A-\). With text \(x more\) after the last keyword shown. X is the number of keywords the study has.
* When the user clicks fo ‘Read more’, they get x \(to be determined\) characters with spaces of abstract \(to be discussed\).

‌

**Comment by markusjt** [comment]
@MortenSikt @KristinaS4 
> * Shorten abstract to 380 characters in the list.
> * When the user clicks fo ‘Read more’, they get x (to be determined) characters with spaces of abstract (to be discussed).

Currently it goes from 500 characters to **all** characters after clicking 'Read more'.
After these changes it would go from 380 characters to **x** characters after clicking 'Read more'. What should the x be here? Or is it still better to just show the whole abstract after clicking 'Read more'?

> * Add keywords below. Cut-off point for keywords: max 7 keywords, random chosen (so as not to have always ones from A-). With text (x more) after the last keyword shown. X is the number of keywords the study has.

At first I didn't think I needed any clarification for this but I guess now the question actually is if these should also have the link to ELSST?

**Comment by MortenSikt** [comment]
For abstracts:

Some of them are extremely long, which is probably the main reason for making a cut off here. The primary function of the result list is to be able to identify relevant data, some abstract information is required to do that but not necessarily the whole content in the cases with extreme length. In these cases this information instead disturbs the primary function of the result list.

But clicking read more is an active choice, and the user should be presented with more information than previously. Keeping in line with the information at the detailed study page the number of characters should be 2000 (some checks from me indicates that this ranges from 1950-1980, not sure why it varies) when clicking read more in the result list. The full abstract will still be available at the detailed study page.

Keywords:
If it is possible to have the 7 keywords always be ELSST keywords if they exist in the metadata that would be beneficial and wanted seeing as ELSST keywords is a CESSDA product and something that we wish to promote. There is no need that the "x more" text includes "x more ELSST keywords" and "x more other keywords" this would perhaps just clutter the UI, it can just be "x more"

**Comment by markusjt** [comment]
@MortenSikt These changes certainly took a lot longer than I expected but now the PR is ready and there's an example image below. 

> Keeping in line with the information at the detailed study page the number of characters should be 2000 (some checks from me indicates that this ranges from 1950-1980, not sure why it varies) when clicking read more in the result list.

This variance is due to #436 (or rather some previous commit since it was already implemented when I looked into it in that issue). Max characters are now 380 before expanding and 2000 after expanding.

> If it is possible to have the 7 keywords always be ELSST keywords if they exist in the metadata

This is technically possible but I decided against it since we don't immediately know which ones are ELSST keywords and changing the keywords while adding ELSST links didn't seem good for user experience (not to mention the added complexity). Now it's just 7 randomly chosen keywords.

I tested different options on how to display the keywords and '(x more)' but ended up going with the simplest solution possible since it also looked the best.
![results_list_example](https://github.com/cessda/cessda.cdc.versions/assets/30312842/944d9032-499c-4f2e-86ac-f875f2d44689)
