### ISSUE TITLE
Change AUSSDA endpoint URL

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#439]
See also #531

**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

From: christian.bischof  
Date: Wed, 13 Apr 2022 at 10:50  
Subject: AW: \[CESSDA\] Bulk metadata validation of your OAI-PMH endpoint  
To: John Shepherdson

Dear John,

I have seen now, CESSDA uses the old url [https://data2.aussda.at](https://data2.aussda.at/), please change to  [https://data.aussda.at](https://data.aussda.at/)

The content is the same.

‌

Best  Christian

**Comment by john-shepherdson** [comment]
Update from Lars on 17/04/2023:

Please test https://data.aussda.at/oai

With

metadataPrefix=oai_ddi&set=all_published

Validation Gate: BASIC

Profile: DDI2.5 PROFILE - MONOLINGUAL 1.0.4


Following up on one of your previous error reports: The more serious issues with the OVAL BASE validator have been fixed by the Dataverse community and will be resolved with the next upgrade in version 13 of Dataverse.

**Comment by john-shepherdson** [comment]
@MortenSikt Yes, that is fine
