### ISSUE TITLE
Potential enhancements to relPubl display

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#502]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Some potential enhancements for the display of relate publications in the UI. To note: some may not be needed after the profiles include this element. To consider in 2023, to be assigned first to the new Service Owner.

1. If there is no <holdings> URI or <extLink> URI, the IDNo often displays a link. So the order of precedence:

* Display the extLink URI
* Display the holdings URI
* Make the IDNo a link.

This would allow the link if the metadata is of this kind:

![](https://bitbucket.org/repo/oLgpneG/images/776464037-image.png)
‌

2\. Publications are now displayed according to their language tag. If language tag is ‘fi’, it is displayed on the Finnish catalogue. For users, it would be really useful to see all relPubl that are in English. So CDC to show all relPubl with ‘en’ tags in all languages catalogues.

Note: the language tags of publications are often wrong. Need to remind SPs to correct them in Tools Open Hour and make issues for metadata.office issue tracker for specific SPs.

This issue is related to ~~#471~~ and ~~#474~~.

Another, easier alternative is to show all publications in all language catalogues.

For the new SO to consider.

**Comment by markusjt** [comment]
@KristinaS4 I have a [PR](https://github.com/cessda/cessda.cdc.searchkit/pull/297) pretty much ready for second part of the issue but a few questions about possible changes before I mark it ready.

The changes I've made always get all the related publications from all languages on the detail page. Would it be better to get extra related publications from English only? Not part of the original issue description but should it be shown somehow on the UI when the language changes from one relpub to another? I have only added lang attribute on the elements.

First part of the issue doesn't seem to be worth the effort from my findings. Almost all SPs are either using ExtLink or holdings or don't have related publications in the first place. I could only find very few related publications that would have proper url in IDNo if they didn't have it in extLink or holdings. There are a lot of studies that have proper url in both IDNo and extLink/holdings but then we are already getting it from extLink/holdings.
Maybe we could simply look for http(s) in IDNo if there's no extLink/holdings but that's the most we should do I think. Trying to otherwise detect if IDNo can be made into a link is not really viable. [This Dataverse export](https://data.sciencespo.fr/api/datasets/export?exporter=ddi&persistentId=doi%3A10.21410/7E4/ETUJUY) is the best example that would benefit from this but is this is an issue in ProgedoCDSP metadata or an issue in Dataverse export? Either way feels like it would be better to change it there instead of adding code to support this when it's such a rare issue overall.

**Comment by KristinaS4** [comment]
@markusjt In the user group it was agreed that we should display all related publications from all languages on the detailed study page regardless of the selected language. I am not sure what you mean about extra related publications from English only? Can you specify?

I agree with you about the first part nor being worth the effort.

**Comment by markusjt** [comment]
> I am not sure what you mean about extra related publications from English only? Can you specify?

I meant "extra" as in compared to what we're displaying now so basically just meant getting English vs all languages (in the original issue all languages was the secondary option) but you already answered this:

> In the user group it was agreed that we should display all related publications from all languages on the detailed study page regardless of the selected language.

So we'll display all related publications from all languages, thanks! I'll make a few changes according to Matthew's comments on the PR before merging this.

**Comment by matthew-morris-cessda** [comment]
Probably better to fix on the indexer side by merging all language entries into a single list, discarding duplicates in the process. It also prevents us from doing the same operation in multiple places and simplifies Searchkit. Do you want me to do this?

**Comment by markusjt** [comment]
> Probably better to fix on the indexer side by merging all language entries into a single list, discarding duplicates in the process. It also prevents us from doing the same operation in multiple places and simplifies Searchkit. Do you want me to do this?

If you could, please, thanks!

Would [this study](https://datacatalogue.cessda.eu/detail?lang=fi&q=ac96a26624d994cbb4387d4c1825b723748b52df9e258b331d1205a876a3b86c) for example then have 0 related publications with Finnish selected before [#297 PR](https://github.com/cessda/cessda.cdc.searchkit/pull/297) is also merged? Which would then show the related publications from en again on the fi page. That's the original assumption I had when making the changes in Searchkit but somehow I missed this case until now.

**Comment by matthew-morris-cessda** [comment]
I'll remove the alternate language copying behaviour from the indexer so that the language information is conserved in Searchkit

**Comment by markusjt** [comment]
Thanks! I'll test the Searchkit PR with the updated indexer on my dev server when it's ready.

I'll also look into sorting related publications by date (newest on top) like discussed in User Group.
