### ISSUE TITLE
User is interested in identifying how many studies exist for a specific language

### ISSUE THREAD

**Issue by KristinaS4** [cessda/cessda.cdc.versions#586]
**As a user I am interested in finding the studies that exist for a specific language**

1. I use the language selection functionality next to the search box:

![image](https://github.com/cessda/cessda.cdc.versions/assets/112862817/8a4042c5-d404-436d-9aec-a90c9660b0d5)

2. I expect to see studies in the selected language:

![image](https://github.com/cessda/cessda.cdc.versions/assets/112862817/087aec38-90cc-47ec-89b3-b08b708a6757)

**Comment by toni-sissala** [comment]
Some languages that can be selected in the drop down return no results. Try "Czech" for example. Is that an error in CDC?

If it is not an error, then I can write a test that selects a language (French, German, Finnish) that presumably returns some studies. Howeve, if CDC is not populated by studies with that language then the test will fail, because no results are found.

**Comment by KristinaS4** [comment]
As far as I can see all the studies from the Czech archive is in English so it seems fair that there are no studies in Czech. However, I am not sure why there is the option to select Czech in the drop down menu if there are no studies in that language. Maybe @john-shepherdson knows if the Czech archive was or is planning to send any studies in Czech to CDC?
