### ISSUE TITLE
New DDI fields @ CDC

### ISSUE THREAD

**Issue by kpapag** [cessda/cessda.cdc.versions#606]
New DDI Fields are to be added @ CDC as part of the EOSC project with ARIA and OpenAIRE. This is a preparation of how will these be represented.

CDC will use the same Access Rights vocabulary as OpenAIRE. The name of the vocabulary is “info:eu-repo-Access-Terms vocabulary”. Only the codes “restrictedAccess” and “openAccess” will be used.

/codeBook/stdyDscr/dataAccs/useStmt/restrctn -> "general free text"

/codeBook/stdyDscr/dataAccs/useStmt/conditions -> OpenAIRE Vocabulary

/codeBook/stdyDscr/dataAccs/useStmt/specPerm/@URI -> application form URL

/codeBook/stdyDscr/dataAccs/useStmt/specPerm  -> more information

examples

`<conditions elementVersion=”info:eu-repo-Access-Terms vocabulary”>restrictedAccess</conditions>`

`<specPerm URI=”https://www.link-to-form.com”>some text</specPerm>`

there is already a test set from SoDaNet Dev Datacatalogue

https://dev-datacatalogue.sodanet.gr/oai?verb=ListIdentifiers&set=SODADEV-CESSDA-ARIA&metadataPrefix=oai_ddi

**Comment by john-shepherdson** [comment]
@kpapag Please provide IDs of some studies that contain magic links

**Comment by john-shepherdson** [comment]
I cannot find either in https://datacatalogue-dev.cessda.eu (which harvested from the SoDaNet DEV endpoint last night).
Have you made them available via OAI-PMH?

**Comment by matthew-morris-cessda** [comment]
I've added the new endpoint under the `SoDaNet-ARIA` code with a friendly name of "SoDaNet - ARIA DEV ENDPOINT". See https://github.com/cessda/cessda.cdc.aggregator.deploy/commit/b7215d1308cee5f2d3b6e5a4e3280bfd75e4d629.

**Comment by john-shepherdson** [comment]
@matthew-morris-cessda The UI updates need to be in place and tested by Monday 11 September at the very latest. Is that achievable?

**Comment by matthew-morris-cessda** [comment]
@kpapag  I've noticed that the URIs are invalid. The errors reported are as follows

- doi:10.17903/FK2/HP56HH - `java.net.URISyntaxException: Illegal character in query at index 145: https://beta.structuralbiology.eu/submit-proposal/new?platform_reference=https://dev-datacatalogue.sodanet.gr/oai:ARIA-TEST&acid=165&machine=a:1:{s:9:"aria-test";a:1:{i:0;s:64:"https://dev-datacatalogue.sodanet.gr/oai:doi:10.17903/FK2/HP56HH`
- doi:10.17903/FK2/TOJ7AH - `java.net.URISyntaxException: Illegal character in query at index 145: https://beta.structuralbiology.eu/submit-proposal/new?platform_reference=https://dev-datacatalogue.sodanet.gr/oai:ARIA-TEST&acid=165&machine=a:1:{s:9:"aria-test";a:1:{i:0;s:64:"https://dev-datacatalogue.sodanet.gr/oai:doi:10.17903/FK2/TOJ7AH`

This is caused by the presence of `{` and `}` characters, which are disallowed in valid URIs (see https://www.ietf.org/rfc/rfc2396.html#section-2.4.3). The URI format should either escape these characters or use different ones.

**Comment by matthew-morris-cessda** [comment]
Yes, these characters will be fine if escaped

**Comment by matthew-morris-cessda** [comment]
Very quickly

**Comment by matthew-morris-cessda** [comment]
![image](https://github.com/cessda/cessda.cdc.versions/assets/68543725/2f260516-c58b-4225-bed5-ed674679ac91)

An example of how this will look when fully implemented.

**Comment by matthew-morris-cessda** [comment]
The URIs still have issues as they contain the `"` character, which isn't allowed.
