### ISSUE TITLE
CDC -> ELSST integration

### ISSUE THREAD

**Issue by MortenSikt** [cessda/cessda.cdc.versions#617]
CDC SO, ELSST SO and CESSDA discussed the posibilities of creating integrations between the services. From the CDC end, there is a desire to be able to access information on ELSST keywords, and utilize the ELSST UI to discover other keywords, which in turn can be searched for in CDC.

In order to create this possibility there needs to be a path from the CDC to ELSST which first need to consider the following:

- Needs to be a string search (since identifiers are not present in metadata from SPs)
- Needs to be able to handle multilingual keywords

The string search can be solved by using the ELSST API to find the correct term in ELSST. Information on language of the keyword clicked can be extracted from metadata at CDC end. ELSST URLs have "clang=language code" at the end, which enables the user to get the same language as the one they clicked in CDC.

Secondly, not all keywords used by SPs are from ELSST. The best experience for the user is if this functionality is only present for valid ELSST keywords. To do this, the CDC needs to check if the keywords present in a metadata record are valid ELSST keywords. Matthew mentioned that a lookup can be done for all the keywords present on a study landing page. There might be some performance concerns here with the requests required to do this lookup, so this should be considered in the solution. A mentioned option is to use caching.

Thirdly, the path from CDC to ELSST, should not replace the existing functionality of filtering directly in the CDC. I.e. clicking a keyword on a landing page and getting a new result page with all studies containing that keyword. So there needs to be a good solution in the UI for how to handle this (also needs to be technically possible)

Suggestion 1: add 2 links under the keyword which is displayed at the landing page. For keywords only present in CDC, only the CDC link is shown:

![image](https://github.com/cessda/cessda.cdc.versions/assets/116061162/3594763e-3c85-4234-b90b-7f43c9c1f74d)

Suggestion 2: the box with the links is shown after the user clicks the keyword, adds a 2nd step to the process but it will not be that invasive on the UI. Will require a reshuffling of the list after the click. If the keyword clicked does not exist in ELSST, the CDC executes a filter search on the keyword:

![image](https://github.com/cessda/cessda.cdc.versions/assets/116061162/d33d4252-dddf-4591-86ca-270ca6154cba)

Suggestion 3: the box with the links is shown as a popup window after the user clicks the keyword avoiding the reshuffling of the list. If the keyword clicked does not exist in ELSST, the CDC executes a filter search on the keyword:

![image](https://github.com/cessda/cessda.cdc.versions/assets/116061162/5f21b39c-b55b-44f5-8e40-32335b0f668c)

**Comment by john-shepherdson** [comment]
Step 1 is to create a mechanism for checking if a given keyword exists in ELSST

**Comment by matthew-morris-cessda** [comment]
Step 1 has been implemented, but without caching at the moment.

A demo UI has been implemented at https://github.com/cessda/cessda.cdc.searchkit/tree/feature/617-cdc-elsst-integration which changes any detected ELSST terms from internal CDC links to ELSST links.

**Comment by matthew-morris-cessda** [comment]
Caching has been implemented server-side

**Comment by MortenSikt** [comment]
Not sure if it is possible to have the metadata language carry over from CDC to ELSST, meaning a user clicking a keyword in a specific language in CDC should be taken to that specific language in ELSST. Currently the user is always brought to the english term, independant of metadata language in CDC. See examples

[Example study 1](https://datacatalogue-staging.cessda.eu/detail?lang=fi&q=52d3f05f8abb7cec6e6c68121e821df3a804892a6761c1ae15d2b3256b994b06) Clicking the term Nuorisorikollisuus leads to [Juvenile Deliquency](https://thesauri.cessda.eu/elsst-4/en/page/b5f727f0-2a03-4790-a79f-ec0b442b9752) in ELSST, where it instead should be [Nuorisorikollisuus ](https://thesauri.cessda.eu/elsst-4/en/page/b5f727f0-2a03-4790-a79f-ec0b442b9752?clang=fi) in ELSST. With the "?clang=fi" in the URL

[Example study 2](https://datacatalogue-staging.cessda.eu/detail?lang=de&q=82b3acecd56c9269a3e40508e87ca9bf0f90de816ef54eef6acfd61059516cad) Clicking the term Gesundheit leads to [Health](https://thesauri.cessda.eu/elsst-4/en/page/91c1b36f-85ff-4345-9678-86a4950fe57a) in ELSST, where it instead should be [Gesundheit](https://thesauri.cessda.eu/elsst-4/en/page/91c1b36f-85ff-4345-9678-86a4950fe57a?clang=de). With the "?clang=de" in the URL

[Example study 3](https://datacatalogue-staging.cessda.eu/detail?lang=el&q=272ae172b48c93c524178905adccf09761a6baabfa2de5f2bdf0019a9988b92c) Clicking the term ΣΤΑΣΕΙΣ (ΑΝΤΙΛΗΨΕΙΣ) leads to [Attitudes](https://thesauri.cessda.eu/elsst-4/en/page/6b792ea3-35c2-457a-b422-01f23c084b90) in ELSST, where it instead should be [ΣΤΑΣΕΙΣ (ΑΝΤΙΛΗΨΕΙΣ)](https://thesauri.cessda.eu/elsst-4/en/page/6b792ea3-35c2-457a-b422-01f23c084b90?clang=el). With the "?clang=el" in the URL

**Comment by markusjt** [comment]
It is possible by adding ```clang``` parameter like you mentioned but the problem is that it can't simply be added to the ```uri``` given by ELSST's API. Using the first example, it is searched with https://thesauri.cessda.eu/rest/v1/elsst-4/lookup?label=NUORISORIKOLLISUUS&lang=fi which results in:
```json
{
  "@context": {
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "uri": "@id",
    "type": "@type",
    "onki": "http://schema.onki.fi/onki#",
    "results": {
      "@id": "onki:results"
    },
    "prefLabel": "skos:prefLabel",
    "altLabel": "skos:altLabel",
    "hiddenLabel": "skos:hiddenLabel",
    "@language": "fi"
  },
  "result": [
    {
      "uri": "https://elsst.cessda.eu/id/4/b5f727f0-2a03-4790-a79f-ec0b442b9752",
      "type": ["skos:Concept"],
      "localname": "b5f727f0-2a03-4790-a79f-ec0b442b9752",
      "prefLabel": "NUORISORIKOLLISUUS",
      "lang": "fi",
      "vocab": "elsst-4"
    }
  ]
}

```
The ```uri``` from ```result``` here is https://elsst.cessda.eu/id/4/b5f727f0-2a03-4790-a79f-ec0b442b9752 and adding ```?clang=fi``` to it doesn't work (404 not found). The link without ```clang``` parameter gets redirected to https://thesauri.cessda.eu/elsst-4/en/page/b5f727f0-2a03-4790-a79f-ec0b442b9752 when opened but the full redirect chain when checked with curl is:
```
$ curl -v -L https://elsst.cessda.eu/id/4/b5f727f0-2a03-4790-a79f-ec0b442b9752 2>&1 | grep -i "^< location:"
< location: https://thesauri.cessda.eu/entity?vocab=elsst-4&uri=https://elsst.cessda.eu/id/4/b5f727f0-2a03-4790-a79f-ec0b442b9752
< location: https://thesauri.cessda.eu/elsst-4/page/b5f727f0-2a03-4790-a79f-ec0b442b9752
< location: https://thesauri.cessda.eu/elsst-4/en/page/b5f727f0-2a03-4790-a79f-ec0b442b9752
```
Parameter ```clang``` works when added to https://thesauri.cessda.eu/elsst-4/page/b5f727f0-2a03-4790-a79f-ec0b442b9752?clang=fi (still redirects to the next location) or https://thesauri.cessda.eu/elsst-4/en/page/b5f727f0-2a03-4790-a79f-ec0b442b9752?clang=fi (the final location).

Easiest solution would be to have ```https://thesauri.cessda.eu/elsst-4/en/page/``` as a variable in CDC and add ```localname``` value from JSON to it along with ```?clang=fi``` so basically in code it would be something like:
```JavaScript
`${ELSST_URL}/${results.result[0].localname}?clang=${lang}`
```
and end up as:
```
https://thesauri.cessda.eu/elsst-4/en/page/b5f727f0-2a03-4790-a79f-ec0b442b9752?clang=fi
```
Currently there is:
```JavaScript
const SKOSMOS_URL = process.env.SEARCHKIT_SKOSMOS_URL || "https://thesauri.cessda.eu";
const ELSST_VOCABULARY = process.env.SEARCHKIT_ELSST_VOCABULARY || "elsst-4";
```
so basically ELSST_URL could be:
```JavaScript
const ELSST_URL = process.env.SEARCHKIT_ELSST_URL || `${SKOSMOS_URL}/${ELSST_VOCABULARY}/en/page`;
```
I don't really know much about ELSST so I don't know if there is some better solution to this. I can see configuring ELSST_URL like this causing issues if the ```uri``` returned by API gets redirected to even slightly different address in the future since it wouldn't be used here anymore so it would require updating the value in ELSST_URL to reflect the change.

**Comment by matthew-morris-cessda** [comment]
Unfortunatly Skosmos doesn't support specifying a language when using the `/entity` API. It's unfortunate because using redirects like this is the officially prescribed way to do this, see https://github.com/NatLibFi/Skosmos/wiki/ServingLinkedData.

We could specify a known prefix (ideally set with an environment variable) that is trimmed from the start of the URIs so we are left with only the UUIDs, and then use that to construct the final URLs directly

**Comment by MortenSikt** [comment]
Thank you for the detailed clarification Markus, we understand now why it does not work. As for both of your proposals, I think you are best left to chose this. But it seems like a good idea to avoid anything that might be vulnerable to a change down the line, but seeing as both these services are CESSDA that perhaps can easily avoided.

**Comment by matthew-morris-cessda** [comment]
It's an ELSST issue that I'm currently investigating

**Comment by matthew-morris-cessda** [comment]
See https://github.com/cessda/cessda.elsst.skosmos/issues/56
