### ISSUE TITLE
Remove DANS endpoint from production

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#662]
DANS endpoint configuration was withheld from 3.4.0  release, but it appears that it found its way into the 3.5.0 release.
DANS records in both Dutch and English can be seen in the English language selection. 
The SO would like the DANS endpoint and associated records to be removed from production and excluded from future releases, until further notice.

**Comment by matthew-morris-cessda** [comment]
DANS removed from production

**Comment by john-shepherdson** [comment]
We could use the sets as above, but would have to treat them as 2 different endpoints with different names and different default languages. Might be confusing for the users to see publishes called (for example) 'DANS-KNAW (English)' and 'DANS-KNAW (Dutch)' - also the names would not comply with the Publisher names CV (https://vocabularies.cessda.eu/vocabulary/CdcPublisherNames?lang=en)

**Comment by RicardaBraukmann** [comment]
Thanks @john-shepherdson for looking into it. For us I would prefer to be included in some way so as soon as possible so if what you say is possible that would be great. Alternatively, you could also for now harvest the English records only as those will be most relevant for CDC users I believe and that set is also our bigger set from the two. 

Of course we want to be included full as soon as possible so it would be great if  we can discuss how that can be achieved. 

Can you specify what we need to do in order to be harvested through our regular endpoint?

We have language of metadata information in our metadata in a custom block so the information is available for most datasets. I am not sure how you harvest the Dataverse instances (i.e. what metadata schema do you use), and what adjustments we would need to make to comply with the requirements? 
I am happy to connect you with our technical team as well as they know better how things are currently implemented.

**Comment by matthew-morris-cessda** [comment]
Discussion about re-adding DANS metadata to CDC should be discussed in a separate issue

**Comment by john-shepherdson** [comment]
See #667 re adding DANS endpoint
